---
title: "Solucion Prueba"
format: html
editor: visual
---

## Ejercicios sobre manipulacion de datos

### Ejercicio 1: Comprension y Manipulacion de Bases de Datos

Lectura de la base:

```{python}

df = pd.read_csv('../data/INEC_Encuesta Estructural Empresarial_Tomo I_2021.csv', delimiter = ';')

```

Seleccionar las variables y mostrar las 10 primeras filas:

```{python}

# Codigo

```

### **Ejercicio 2: Generacion de estadisticas de resumen**

Cargamos las librerias de para trabajar en python:

```{python}
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sys
```

Mostramos la version de python con que trabajamos:

```{python}
print(sys.version)
```

Con la base ya importada anteriormente procedemos a obtener la estadistica descriptiva de la variable de trabajadores afiliados en la empresa:

```{python}
df.rename(columns={'v5090':'tafiliados'}, inplace=True)
print (df['tafiliados'].describe())
```

Ahora se procede a obtener el numero de empresas por provincia:

```{python}
provincias ={
    1:'Azuay',
    2:'Bolivar',
    3:'Cañar',
    4:'Carchi',
    5:'Cotopaxi',
    6:'Chimborazo',
    7:'El Oro',
    8:'Esmeraldas',
    9:'Guayas',
    10:'Imbabura',
    11:'Loja',
    12:'Los Rios',
    13:'Manabi',
    14:'Morona Santiago',
    15:'Napo',
    16:'Pastaza',
    17:'Pichincha',
    18: 'Tungurahua',
    19: 'Zamora Chinchipe',
    20: 'Galapagos',
    21: 'Sucumbios',
    22: 'Orellana',
    23: 'Santo Domingo de los Tsachilas',
    24: 'Santa Elena'}

df['des_provincias'] = df['provincia'].map(provincias)

conteo_provincia = df.groupby('des_provincias')['id_empresa'].count()
print(conteo_provincia)
```

### Ejercicio 3: Comparacion de grupos dentro de los datos

### **Ejercicio 4: Analisis de Patrones**

Ahora creamos una tabla de frecuencias por provincias de empresas que tienen mas de 50 empleados:

```{python}
df_50trab = df[df['tafiliados'] > 50 ]
tab_freq_emp = df_50trab.groupby('des_provincias')['id_empresa'].count()
acumulado = tab_freq_emp.cumsum()
freq_df = pd.concat([tab_freq_emp, acumulado], axis=1)
freq_df.columns = ['Frequencia', 'Frecuencia Acumulada']
print(freq_df)
```

Calculando entonces tambien el porcentaje de empresas con mas de 50 empleados por provincia:

```{python}
total = df.groupby('des_provincias')['id_empresa'].nunique()
porcentaje = tab_freq_emp / total 

resumen = pd.concat([tab_freq_emp, acumulado, porcentaje], axis=1)
resumen.columns = ['Frecuencia', 'Frecuencia Acumulada', 'Porcentaje']

print(resumen)
```

## Ejercicios sobre visualizacion de datos

### Ejercicio 1: Diagrama de barras por provincia

### Ejercicio 2: Diagrama de dispersion del numero de empresas y su valor agregado bruto
